{% set name = "lapy" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lapy-{{ version }}.tar.gz
  sha256: f429b84aa0a4bf46cbee03ccb86bb5f12017c98cee86891cb73be1c412ca1ddc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - lapy-sys_info = lapy.commands.sys_info:run

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0.0
  run:
    - nibabel
    - numpy >=2
    - plotly
    - psutil
    - python >={{ python_min }}
    - scikit-sparse >=0.4.16
    - scipy

test:
  imports:
    - lapy
  commands:
    - pip check
    - lapy-sys_info --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Deep-MI/LaPy
  summary: Toolbox for Differential Geometry on Triangle and Tetrahedra Meshes (FEM, Laplace, Poisson, Heat Flow ...).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - m-reuter
    - mscheltienne
