{% set name = "lapy" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lapy-{{ version }}.tar.gz
  sha256: a956a55be149c8e693d6e734d7dfd6e5f97941f571ab5c9eb5576bd8455a6af4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - lapy-sys_info = lapy.commands.sys_info:run

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.0.0
  run:
    - nibabel
    - numpy >=1.22
    - plotly
    - psutil
    - python >=3.8
    - scikit-sparse
    - scipy

test:
  imports:
    - lapy
  commands:
    - pip check
    - lapy-sys_info --help
  requires:
    - pip

about:
  home: https://github.com/Deep-MI/LaPy
  summary: Toolbox for Differential Geometry on Triangle and Tetrahedra Meshes (FEM, Laplace, Poisson, Heat Flow ...).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - m-reuter
    - mscheltienne
