{% set name = "lapy" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lapy-{{ version }}.tar.gz
  sha256: a0fb9228be4dbe5890d4fbbe9e162ad88d6496df4b8c263f6b8cc86f1e541157

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - lapy-sys_info = lapy.commands.sys_info:run

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0.0
  run:
    - nibabel
    - numpy >=1.22
    - plotly
    - psutil
    - python >={{ python_min }}
    - scikit-sparse
    - scipy

test:
  imports:
    - lapy
  commands:
    - pip check
    - lapy-sys_info --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Deep-MI/LaPy
  summary: Toolbox for Differential Geometry on Triangle and Tetrahedra Meshes (FEM, Laplace, Poisson, Heat Flow ...).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - m-reuter
    - mscheltienne
